[build-system]
requires = [
  "setuptools>=62.1",
  "setuptools_scm[toml]>=6.2",
  "wheel",]
build-backend = "setuptools.build_meta"

[project]
name = "sunkit-magex"
description = "Potential field source surface modelling"
readme = "README.rst"
requires-python = ">=3.9"
license = { file = "licenses/LICENSE.rst", content-type = "text/plain" }
authors = [
  { name = "The SunPy Community", email = "sunpy@googlegroups.com" },
]
dependencies = []
dynamic = ["version"]

[project.optional-dependencies]
tests = [
    "pytest",
    "pytest-doctestplus",
    "pytest-cov",
]
docs = [
    "sphinx",
    "sphinx-automodapi",
    "tomli; python_version <\"3.11\"",
]

[project.urls]
repository = "https://sunpy.org"

[tool.setuptools]
zip-safe = false
include-package-data = true

[tool.setuptools.packages.find]

[tool.setuptools_scm]
write_to = "sunkit-magex/_version.py"

[tool.pytest.ini_options]
testpaths = [
  "sunkit-magex",
  "docs",
]
doctest_plus = "enabled"
text_file_format = "rst"
addopts = "--doctest-rst"

[tool.coverage.run]
omit = [
 "sunkit-magex/__init*",
 "sunkit-magex/conftest.py",
 "sunkit-magex/*setup_package*",
 "sunkit-magex/tests/*",
 "sunkit-magex/*/tests/*",
 "sunkit-magex/extern/*",
 "sunkit-magex/version*",
 "*/sunkit-magex/__init*",
 "*/sunkit-magex/conftest.py",
 "*/sunkit-magex/*setup_package*",
 "*/sunkit-magex/tests/*",
 "*/sunkit-magex/*/tests/*",
 "*/sunkit-magex/extern/*",
 "*/sunkit-magex/version*",
]

[tool.coverage.report]
exclude_lines = [
  # Have to re-enable the standard pragma
  "pragma: no cover",
  # Don't complain about packages we have installed
  "except ImportError",
  # Don't complain if tests don't hit assertions
  "raise AssertionError",
  "raise NotImplementedError",
  # Don't complain about script hooks
  "def main(.*):",
  # Ignore branches that don't pertain to this version of Python
  "pragma: py{ignore_python_version}",
  # Don't complain about IPython completion helper
  "def _ipython_key_completions_",
]
